/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RespiroRouteImport } from './routes/respiro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerRelatoriosRouteImport } from './routes/manager/relatorios'
import { Route as ManagerEquipesRouteImport } from './routes/manager/equipes'

const RespiroRoute = RespiroRouteImport.update({
  id: '/respiro',
  path: '/respiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRelatoriosRoute = ManagerRelatoriosRouteImport.update({
  id: '/manager/relatorios',
  path: '/manager/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerEquipesRoute = ManagerEquipesRouteImport.update({
  id: '/manager/equipes',
  path: '/manager/equipes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/habitos': typeof HabitosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/respiro': typeof RespiroRoute
  '/manager/equipes': typeof ManagerEquipesRoute
  '/manager/relatorios': typeof ManagerRelatoriosRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/habitos': typeof HabitosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/respiro': typeof RespiroRoute
  '/manager/equipes': typeof ManagerEquipesRoute
  '/manager/relatorios': typeof ManagerRelatoriosRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/habitos': typeof HabitosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/respiro': typeof RespiroRoute
  '/manager/equipes': typeof ManagerEquipesRoute
  '/manager/relatorios': typeof ManagerRelatoriosRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diario'
    | '/habitos'
    | '/login'
    | '/perfil'
    | '/respiro'
    | '/manager/equipes'
    | '/manager/relatorios'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diario'
    | '/habitos'
    | '/login'
    | '/perfil'
    | '/respiro'
    | '/manager/equipes'
    | '/manager/relatorios'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/diario'
    | '/habitos'
    | '/login'
    | '/perfil'
    | '/respiro'
    | '/manager/equipes'
    | '/manager/relatorios'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiarioRoute: typeof DiarioRoute
  HabitosRoute: typeof HabitosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RespiroRoute: typeof RespiroRoute
  ManagerEquipesRoute: typeof ManagerEquipesRoute
  ManagerRelatoriosRoute: typeof ManagerRelatoriosRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/respiro': {
      id: '/respiro'
      path: '/respiro'
      fullPath: '/respiro'
      preLoaderRoute: typeof RespiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/relatorios': {
      id: '/manager/relatorios'
      path: '/manager/relatorios'
      fullPath: '/manager/relatorios'
      preLoaderRoute: typeof ManagerRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/equipes': {
      id: '/manager/equipes'
      path: '/manager/equipes'
      fullPath: '/manager/equipes'
      preLoaderRoute: typeof ManagerEquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiarioRoute: DiarioRoute,
  HabitosRoute: HabitosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RespiroRoute: RespiroRoute,
  ManagerEquipesRoute: ManagerEquipesRoute,
  ManagerRelatoriosRoute: ManagerRelatoriosRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
