ALTER TABLE habits
  ADD COLUMN IF NOT EXISTS mood          TEXT,
  ADD COLUMN IF NOT EXISTS movement_minutes INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS energy_level  INT NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS meals         JSONB DEFAULT '[]'::jsonb;
